name       : retext
version    : 8.0.1
release    : 18
source     :
    - https://github.com/retext-project/retext/archive/refs/tags/8.0.1.tar.gz : 8381672537b6f4dcb437a1d42aae55e87415bb6ef05d6dec33922a7fec368bcd
homepage   : https://github.com/retext-project/retext
license    : GPL-2.0-or-later
component  : editor
summary    : Simple but powerful editor for Markdown and reStructuredText
description: |
    ReText is a simple but powerful editor for Markdown and reStructuredText markup languages. ReText is written in Python language and works on Linux and other POSIX-compatible platforms.
builddeps  :
    - pkgconfig(Qt6UiTools)
    - pygments              # check
    - pymarkups             # check
    - python-chardet        # check
    - python-docutils       # check
    - python-qt6            # check
    - xorg-server-xvfb      # check
rundeps    :
    - pyenchant
    - pygments
    - pymarkups
    - python-chardet
    - python-docutils
    - python-pyqt6-webengine
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        xvfb-run python3 setup.py test
    popd
