name       : retext
version    : 7.0.4
release    : 5
source     :
    - https://github.com/retext-project/retext/archive/7.0.4.tar.gz : dd9358dd541266eadf7b4f4606b1eb0a98fa321c25f58f1a9917ec4600345fad
license    : GPL-3.0-or-later
component  : editor
summary    : Simple but powerful editor for Markdown and reStructuredText
description: |
    ReText is a simple but powerful editor for Markdown and reStructuredText markup languages.
    ReText is written in Python language and works on Linux and other POSIX-compatible platforms.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(python3)
    - pygments
    - pymarkups
    - python-chardet
    - python-docutils
    - python-markdown
    - python3-qt5
    - xorg-server-xvfb
rundeps    :
    - pyenchant
    - pymarkups
    - python-chardet
    - python-docutils
    - python-markdown
    - python3-qt5
setup      : |
    lrelease locale/*.ts
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        xvfb-run python3 setup.py test
    popd
