name       : retext
version    : 8.0.0
release    : 15
source     :
    - https://github.com/retext-project/retext/archive/refs/tags/8.0.0.tar.gz : d0ab71b60c20c88558504e6128245c735614da0f4151602c3196ef88ac28e3d7
homepage   : https://github.com/retext-project/retext
license    : GPL-3.0-or-later
component  : editor
summary    : Simple but powerful editor for Markdown and reStructuredText
description: |
    ReText is a simple but powerful editor for Markdown and reStructuredText markup languages. ReText is written in Python language and works on Linux and other POSIX-compatible platforms.
builddeps  :
    - pkgconfig(Qt6UiTools)
    - pymarkups             # check
    - python-chardet        # check
    - python-docutils       # check
    - python-qt6            # check
    - xorg-server-xvfb      # check
rundeps    :
    - pyenchant
    - pymarkups
    - python-chardet
    - python-docutils
    - python-pyqt6-webengine
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        xvfb-run python3 setup.py test
    popd
