name       : retext
version    : 7.2.1
release    : 11
source     :
    - https://github.com/retext-project/retext/archive/refs/tags/7.2.1.tar.gz : a1e8784fcb4e186a6e6e42a0f2be4098c27bedb96a9711aa17a9846278e7d932
homepage   : https://github.com/retext-project/retext
license    : GPL-3.0-or-later
component  : editor
summary    : Simple but powerful editor for Markdown and reStructuredText
description: |
    ReText is a simple but powerful editor for Markdown and reStructuredText markup languages. ReText is written in Python language and works on Linux and other POSIX-compatible platforms.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(python3)
    - pymarkups
    - python-chardet
    - python-docutils
    - python3-qt5
    - xorg-server-xvfb
rundeps    :
    - pyenchant
    - pymarkups
    - python-chardet
    - python-docutils
    - python3-qt5
setup      : |
    lrelease locale/*.ts
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        xvfb-run python3 setup.py test
    popd
