name       : retext
version    : 6.0.2
release    : 1
source     :
    - https://github.com/retext-project/retext/archive/6.0.2.tar.gz : 50c02d69ff6dca8863003e913a2acae7f3041e44ea96852e2dac303d435d1ca2
license    : GPL-3.0
component  : editor
summary    : Simple but powerful editor for Markdown and reStructuredText
description: |
    ReText is a simple but powerful editor for Markdown and reStructuredText markup languages.
    ReText is written in Python language and works on Linux and other POSIX-compatible platforms.
builddeps  :
    - qt5-tools
rundeps    :
    - pyenchant
    - pymarkups
    - python-docutils
    - python-markdown
    - python3-qt5
setup      : |
    lrelease locale/*.ts
build      : |
    %python3_setup
install    : |
    %python3_install
