name       : retext
version    : 7.1.0
release    : 8
source     :
    - https://github.com/retext-project/retext/archive/7.1.0.tar.gz : a51cf19232e74a6972ce5d875ed1f24b07e6922841ce04558b99ecfc34b34134
homepage   : https://github.com/retext-project/retext
license    : GPL-3.0-or-later
component  : editor
summary    : Simple but powerful editor for Markdown and reStructuredText
description: |
    ReText is a simple but powerful editor for Markdown and reStructuredText markup languages.
    ReText is written in Python language and works on Linux and other POSIX-compatible platforms.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(python3)
    - pymarkups
    - python-chardet
    - python-docutils
    - python3-qt5
    - xorg-server-xvfb
rundeps    :
    - pyenchant
    - pymarkups
    - python-chardet
    - python-docutils
    - python3-qt5
setup      : |
    lrelease locale/*.ts
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        xvfb-run python3 setup.py test
    popd
